# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ata_piix" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [ "mitigations=off" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dd3ec3e4-291b-4910-aea4-b37d5d1c8e6d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CEF1-4BAD";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-partlabel/home";
      fsType = "ext4";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-label/var";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5d1c3a8d-3bc8-4dce-b213-351ed8bff75b"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
